name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"] # Trigger on pushes to master

permissions:
  contents: read
  pages: write
  id-token: write # Grant the id-token: write permission

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: src/package-lock.json
          node-version: 20 # Or your preferred version
          cache: 'npm'

      - name: Install Dependencies
        run: cd src && npm ci # 'ci' is safer than 'install' for CI environments

      - name: Build Project
        run: cd src && npm run build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './src/out'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # Provides the live site URL
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment  # Add this ID to enable output referencing
        uses: actions/deploy-pages@v4
    
